# Site settings
title: SnagTracker
email: sjoerd@snagtracker.com
description: >
  SnagTracker is super simpele software om in no time de duidelijkste rapporten te maken
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://snagtracker.com" # the base hostname & protocol for your site
twitter_username: snagtracker
github_username:  snagtracker

# Build settings
markdown: kramdown
